spring.application.name=mcpclient

logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers.json
spring.ai.mcp.client.request-timeout=30s
spring.ai.mcp.client.streamable-http.connections.eazybytes.url=http://localhost:8090
spring.ai.mcp.client.streamable-http.connections.eazybytes.endpoint=/mcp